version: "3"

services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # We copy the init.sql file to the container, so that it's executed when the container starts

  destination_postgres: # Destination database can be called data warehouse after the ELT process
    image: postgres:latest
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret

  elt_script:
    build:
      context: ./elt # Directory containing the Dockerfile and pipeline.py
      dockerfile: Dockerfile # Name of the Dockerfile, if it's something other than "Dockerfile", specify here
    command: ["python", "pipeline.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

networks:
  elt_network:
    driver: bridge
